# [START runtime]
runtime: nodejs12
# [END runtime]
#env: flex
service : api

env_variables :
  MONGODB_URI: "mongodb+srv://dileep:dileep@78@cluster0.dk8qw.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  DB_NAME: "clients"
  ACCESS_TOKEN_SECRET: "f962f5a8b484e3cfa175227cd223fd5e0fc0d8c62f20aec87d918c808c5e833b"
  REFRESH_TOKEN_SECRET: "029f1d279557b277c9beccb35dc0f9e22cefa462b2d3e2af42e386a3e4e68f94"
  VERIFICATION_URI : "https://fifth-pact-312314.uc.r.appspot.com/user/verify/"
  RESTPASSWORD_URI : "https://fifth-pact-312314.uc.r.appspot.com/user/updatepassword/"
  EMAIL : "developer.dileep78@gmail.com"
  EMAIL_PWD : ""
  GCS_BUCKET : "infydealz_bucket"
  ENCRYPT_SECRET_KEY : "skajdfhkljdfhldafkjh12j4h23414"
  EMAIL_CLIENT_ID : "1002041972109-de59716blnv743jfjg3rl27lidfm6fuf.apps.googleusercontent.com"
  EMAIL_CLIENT_SECRET : "5XrOkaCLHNwH2AzEicHamEMO"
  EMAIL_CLIENT_ACCESSTOKEN : "ya29.a0AfH6SMAdGWH-SsZ-aHH0FpWNYMMaAB9gblWCIiRUAqlftQkRu12LfvjaOFPiS9Fij1fgCV45bcS4Emlp8OnWT88WxUM-9_tyoKjIVkUyhZB5b_3uMvtU9ySD_hoQLR_y77ilzDcu2Hs4oMXGZegqAFhjNekR"
  EMAIL_CLIENT_REFRESHTOKEN : "1//04seUIXeYYkTSCgYIARAAGAQSNwF-L9IrZ-guO46-EP2jd2u0cUVVDLTOLuMTaK6CQrQ49-lS75w9GldvLA8eYA9YgABYelpPgXk"
  PAYTM_MID : "ExPUrQ97239134980627"
  PAYTM_WEBSITE : "WEBSTAGING"
  PAYTM_CHANNEL_ID : "WEB"
  PAYTM_INDUSTRY_TYPE_ID : "Retail"
  PAYTM_CALLBACK_URL : "https://api-dot-fifth-pact-312314.uc.r.appspot.com/rest/v1/payment/callback"
  PAYTM_MERCHANT_KEY : "GEv_twPdBvnhtB9Y"
  MERCHANT_APP_URI : "https://fifth-pact-312314.uc.r.appspot.com"


manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10





 